import * as z from "zod";

export const FormSchema = z.object({
  "Application Date": z.string().nonempty("This field is required"),
  "Business Visit Date": z.string().nonempty("This field is required"),
  "Home Visit Date": z.string().nonempty("This field is required"),
  "Credit Committee Date": z.string().nonempty("This field is required"),
  "Applicant Name": z.string().nonempty("This field is required"),
  "Applicant DOB": z.string().nonempty("This field is required"),
  "Applicant Spouse Name": z.string().optional(),
  "Applicant Spouse DOB": z.string().nonempty("This field is required"),
  "Applicant Home Address": z.string().nonempty("This field is required"),
  "Applicant Marital Status": z.string().nonempty("This field is required"),
  "Co-signor": z.string().nonempty("This field is required"),
  "Co-signor Relationship": z.string().nonempty("This field is required"),
  "Business Name": z.string().nonempty("This field is required"),
  "Business Legal Status": z.string().nonempty("This field is required"),
  "Business Activity": z.string().nonempty("This field is required"),
  "Business Activity Age": z.string().nonempty("This field is required"),
  "Business Address": z.string().nonempty("This field is required"),
  "Business Address Age": z.string().nonempty("This field is required"),
  "Guarantor Name": z.string().nonempty("This field is required"),
  "Guarantor Marital Status": z.string().nonempty("This field is required"),
  "Guarantor Activity": z.string().nonempty("This field is required"),
  "Guarantor Activity Age": z.string().nonempty("This field is required"),
  HG: z.string().nonempty("This field is required"),
  BA: z.string().nonempty("This field is required"),
  INV: z.string().nonempty("This field is required"),
  VMG: z.string().nonempty("This field is required"),
  LBMG: z.string().nonempty("This field is required"),
  Others: z.string().nonempty("This field is required"),
  "Loan History": z.array(
    z.object({
      "Loan Amount": z.string().nonempty("This field is required"),
      Tenor: z.string().nonempty("This field is required"),
      Installment: z.string().nonempty("This field is required"),
      "Days in Overdue": z.string().nonempty("This field is required"),
      Year: z.string().nonempty("This field is required"),
    })
  ),
  "Loan Approval": z.string().optional(),
  "Loan Rejection": z.string().optional(),
  "Proposed Amount": z.string().optional(),
  "Applied Amount": z.string().optional(),
  "Proposed Tenor": z.string().optional(),
  "Applied Tenor": z.string().optional(),
  "Proposed Installment": z.string().optional(),
  "Can easily pay": z.string().optional(),
  "Credit Committee Approval": z.string().optional(),
  "Credit Committee Rejection": z.string().optional(),
  "Credit Committee Approved Amount": z.string().optional(),
  "Credit Committee Approved Tenor": z.string().optional(),
  "Credit Committee Applied Amount": z.string().optional(),
  "Credit Committee Applied Tenor": z.string().optional(),
  "Credit Committee Loan Cycle": z.string().optional(),
  "Credit Committee Proposed Installment": z.string().optional(),
  "Credit Committee Can easily pay": z.string().optional(),
  "Credit Committe Size": z.string().nonempty("This field is required"),
  "Credit Committe in Favour": z.string().nonempty("This field is required"),
  "Credit Committe Against": z.string().nonempty("This field is required"),
});

export type FormValues = z.infer<typeof FormSchema>;
